name: bible_study_way
packages:
  - apps/**
  - packages/**

ide:
  intellij:
    enabled: false
    executeInTerminal: false

scripts:
  gen:
    run: melos exec -c 1 --depends-on build_runner -- dart run build_runner build
  gen_all:
    run: melos exec -c 1 --depends-on build_runner -- dart run build_runner build --delete-conflicting-outputs
  gen_loc:
    run: melos exec -c 1 --depends-on flutter_localizations -- flutter gen-l10n
