# build.yaml
# ...

targets:
  $default:
    builders:
      flutter_gen_runner: # or flutter_gen
        options: 
          output: lib/src/gen/
          line_length: 80
          integrations:
            image: true
            flutter_svg: true
            rive: false
            lottie: false