name: bible_study_way
description: Bible Study Way Client
version: 0.0.1+1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^16.0.0
  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  provider: ^6.1.5
  equatable: ^2.0.7
  # Firebase
  firebase_core: ^4.0.0

  # Core
  # Debug Services
  core_debug:
    path: ../../packages/core/debug
  # Config app
  core_config:
    path: ../../packages/core/config
  # Common
  core_common:
    path: ../../packages/core/common
  # Settings app
  core_settings:
    path: ../../packages/core/settings
  # Theme app
  core_theme:
    path: ../../packages/core/theme
  # Localization app
  core_localization:
    path: ../../packages/core/localization
  # Shared widgets and screens
  core_shared:
    path: ../../packages/core/shared

  # Features
  # SplashScreen
  splash:
    path: ../../packages/features/splash
  # Auth: Login, Register, Forgot Password, Reset Password, Verify Email, Verify Phone, Verify Code
  auth:
    path: ../../packages/features/auth
  # Main: Progress, 
  main:
    path: ../../packages/features/main
  # Progress
  progress:
    path: ../../packages/features/progress

  # Lectures
  lectures:
    path: ../../packages/features/lectures
  # Highlights
  highlights:
    path: ../../packages/features/highlights
  # Favorites
  favorites:
    path: ../../packages/features/favorites
  # More
  more:
    path: ../../packages/features/more

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
