name: bible_study_way
description: Bible Study Way Client
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^15.1.3
  # State Management
  flutter_bloc: ^9.1.1
  provider: ^6.1.5

  # Core
  # Debug Services
  debug:
    path: ../../packages/core/debug
  # Config app
  core_config:
    path: ../../packages/core/config
  # Theme app
  core_theme:
    path: ../../packages/core/theme
  # Localization app
  core_localization:
    path: ../../packages/core/localization

  # Features
  # SplashScreen
  splash:
    path: ../../packages/features/splash

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
