# localization packages
# flutter gen-l10n
arb-dir: lib/src/l10n/
template-arb-file: app_en.arb
output-dir: lib/src/l10n/gen
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated_messages.json
nullable-getter: false
synthetic-package: false
