name: domain_profile
description: Domain layer for profile and progress.
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  # Common
  core_common:
    path: ../../core/common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
